version: '3.7'

services:
  app:
    build:
      context: . 
      dockerfile: docker/deploy/Dockerfile
    restart: unless-stopped
    environment:
      DB_ADDRESS: mysql:3306
    depends_on:
      - mysql
    ports:
      - 3000:3000

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: getground
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

